[workspace]
members = [
    "relayer-server",
    "indexer-tx-storage",
    "indexer-worker",
    "indexer-api",
]
default-members = [
    "indexer-worker",
    "indexer-api",
]

[workspace.package]
authors = ["Dmitry Vdovin <voidxnull@gmail.com>"]
edition = "2021"
