version: "3"

services:
  db:
    image: postgres:14.5
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    expose:
      - 5432
  rust:
    image: rust:nightly
    volumes:
      - .:/app
      - db_data:/var/lib/postgresql/data
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres"