#!/usr/bin/env bash

# TODO: Versioning

USERNAME=voidxnull
IMAGE=zeropool-$1-$2

echo $USERNAME/$IMAGE:latest

docker build -f ./docker/Dockerfile.$1 -t $USERNAME/$IMAGE:latest . && \
docker push $USERNAME/$IMAGE:latest